on: [pull_request]

jobs:
  so_clean_job:
    runs-on: ubuntu-latest
    name: Clean my PRs
    steps:
      - name: So clean
        uses: pickleheads/so-clean@v1.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
